### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by ll104567** [TryHackMyOffsecBox/Target-Machines-WriteUp#1]
https://tryhackmyoffsecbox.github.io/Target-Machines-WriteUp/docs/HackMyVM/Challenges/Prog/015#pytohn-%E8%A7%A3%E7%A0%81

python 拼错了

**Comment by Randark-JMT** [comment]
已在 7e765d886d15aee18f9f30248e4a9dfa8e5a276b 中修改

感谢大佬指正
